### ISSUE TITLE
Future roadmap 

### ISSUE THREAD

**Issue by kajov** [cswendrowski/FoundryVTT-Discord-Rich-Presence#29]
Hi I was wondering are you looking to create a future roadmap for the module and finally get the module talk with Desktop app and connect to specified Voice channels instead of using GameSDK from Discord ?

**Comment by cswendrowski** [comment]
Heyo! The limitation of using the GameSDK is a Discord one - Discord does not offer any way to connect Voice / Video with the Desktop Discord app. There's unfortunately nothing I can do about it

Due to this, I have no further plans for this module - it does everything I want it to do out of the GameSDK
